version: '3.8'

services:
  frontend:
    build:
      context: .
    container_name: frontend
    restart: always
    networks:
      - frontend-network
      - app-network
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3001

networks:
  frontend-network:
    driver: bridge
  app-network:
    name: app-network
    driver: bridge